Refactor part of the implementation that checks the link status using ioctl(SIOCGMIIPHY).
It appears that the original source code for mii-tool(8) has
a similar problem: the ifreq.ifr_data is not initialized to point
to user-supplied data storage.

However, attempts to test the original mii-tool(8) implementation compiled
from source code (before and after the fix) fail with the following error:
SIOCGMIIPHY on 'eth0' failed: Operation not supported

The above error is probably because the network interface card doesn't
support MII.

Eventually, the above refactoring fixes a compilation error triggered
by the forthcoming gcc-4.1 described in Bugzilla entry #448

Bugzilla URL:	http://www.xorp.org/bugzilla/show_bug.cgi?id=448
Bug found by:	hasso AT linux.ee (Hasso Tepper)


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@7873 26435e26-4b25-483a-942d-477236992e84