netbsd: Work around pcap header file bugs.
This fixes this error:

g++ -o obj/x86_64-unknown-netbsd6.0./fea/data_plane/io/io_link_pcap.os -c -O2 -g3 -Werror -W -Wall -Wwrite-strings -Wcast-qual -Wpointer-arith -Wcast-align -Woverloaded-virtual -ftemplate-depth-25 -pipe -DXORP_BUILDINFO -fPIC -DXRL_PF=120 -DXORP_VERSION=1.8.5 -Iobj/x86_64-unknown-netbsd6.0. -I. -I. fea/data_plane/io/io_link_pcap.cc
In file included from fea/data_plane/io/io_link_pcap.hh:36:0,
                 from fea/data_plane/io/io_link_pcap.cc:45:
/usr/include/pcap/bpf.h:382:8: error: previous declaration of 'u_int bpf_filter(const bpf_insn*, const u_char*, u_int, u_int)' with 'C++' linkage
/usr/include/pcap.h:354:71: error: conflicts with new declaration with 'C' linkage
/usr/include/pcap/bpf.h:381:6: error: previous declaration of 'int bpf_validate(const bpf_insn*, int)' with 'C++' linkage
/usr/include/pcap.h:355:51: error: conflicts with new declaration with 'C' linkage
scons: *** [obj/x86_64-unknown-netbsd6.0./fea/data_plane/io/io_link_pcap.os] Error 1
scons: building terminated because of errors.

Signed-off-by: Ben Greear <greearb@candelatech.com>