Set the global names for top-level CLI commands. Now the xorpsh CLI prints the appropriate error messages:
ERROR: "commit" does not take any additional parameters.

instead of:

ERROR: "" does not take any additional parameters.

Note that we have to do it explicitly for every (top-level only?)
CLI command, which is not the right solution. This setting should
be done in a generic way inside the CLI library (e.g., the
CliCommand::add_command() methods inside file cli/cli_command.cc).

Bug found by:	Xiaoshuai Yang <eshe168 AT gmail.com>


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@10922 26435e26-4b25-483a-942d-477236992e84