Add explicit casting when directly accessing fields in "struct ip":
ipvx.copy_out(ip->ip_src) ->
ipvx.copy_out(static_cast<struct in_addr&>(ip->ip_src));

The cast is a work-around because of a probably broken
gcc-3.4.2 compiler on FreeBSD-5.3-x that gives the following error:

g++ -DHAVE_CONFIG_H -I. -I. -I.. -I..    -g  -W -Wall -Wwrite-strings
-Wcast-qual -Werror -Wpointer-arith -Wcast-align -Woverloaded-virtual
-ftemplate-depth-20 -c -o mfea_proto_comm.o `test -f mfea_proto_comm.cc
|| echo './'`mfea_proto_comm.cc
mfea_proto_comm.cc: In member function
`int ProtoComm::proto_socket_write(uint16_t, const IPvX&, const IPvX&,
int, int, bool, const uint8_t*, size_t)':
mfea_proto_comm.cc:1521: error: cannot bind packed field `ip->ip::ip_src'
to `in_addr&'
mfea_proto_comm.cc:1522: error: cannot bind packed field `ip->ip::ip_dst'
to `in_addr&'

The reason for the compilation error is because "struct ip" has been
defined as __packed.

Bug found by:	Dikshie <dikshie@lapi.itb.ac.id>


git-svn-id: https://xorp.svn.sourceforge.net/svnroot/xorp@4513 26435e26-4b25-483a-942d-477236992e84